# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Create the directory for allowed files so that the MCP server finds it
RUN mkdir -p /home/user/pinata/files

# Install app dependencies
COPY package*.json ./

RUN npm install --ignore-scripts

# Copy all source files
COPY . .

# Build the application
RUN npm run build

# Command to run the MCP server
CMD ["node", "dist/index.js"]
